services:
  znsfw:
    container_name: znsfw
    image: helloz/znsfw
    # networks:
    #   - mynet
    ports:
      - "7086:7086"
    # 环境变量
    environment:
      - NSFW_TOKEN=xxx
    restart: always