services:
  znsfw:
    container_name: znsfw
    image: helloz/znsfw
    deploy:
      resources:
        limits:
          memory: 600M  # 限制内存
    # networks:
    #   - mynet
    ports:
      - "7086:7086"
    # 环境变量
    environment:
      - NSFW_TOKEN=xxx
    restart: always